[tox]
envlist = py312

[testenv]
runner = uv-venv-lock-runner
commands = python -m unittest

[flake8]
max-line-length = 88
exclude =
    .vercel
    .venv
    node_modules
    # below are the defaults
    .svn
    CVS
    .bzr
    .hg
    .git
    __pycache__
    .tox
