---
version: 2
jobs:
  test_python:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: pip install -r dev-requirements.txt
      - run: black --check .
      - run: flake8
      - run: tox
      - run: pip-compile --no-annotate --no-emit-index-url
      - run: pip-compile --no-annotate --no-emit-index-url dev-requirements.in
      - run: git diff --exit-code -- dev-requirements.txt requirements.txt
  test_javascript:
    docker:
      - image: cimg/node:18.14
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
workflows:
  version: 2
  test:
    jobs:
      - test_python
      - test_javascript
